export const VAULT_HEALTH_PERCENT_GREEN = 125;
export const VAULT_HEALTH_PERCENT_YELLOW = 105;
export const VAULT_HEALTH_PERCENT_RED = 100;

export const VAULT_UTILIZATION_RATIO_GREEN = 90;
export const VAULT_UTILIZATION_RATIO_RED = 100;
